### ISSUE TITLE
get value with cache

### ISSUE THREAD

**Issue by cdupont** [hverr/haskell-cache#11]
Hi,
I have a pattern that comes back often: https://stackoverflow.com/questions/59039737/design-question-cache-mechanism-in-haskell

So I wanted to suggest adding a function that combines lookup and insert: 
```
-- Get a value from cache. If not available from cache, use the provided function and update the cache.
fetchWithCache :: (Eq k, Hashable k) => Cache k v -> k -> (k -> IO v) -> IO v 
fetchWithCache c k f = do
  mv <- lookup c k
  case mv of
    Just v -> return v
    Nothing -> do
       v <- f
       insert c k v
       return v
```
What do you think? If OK I could make a PR.

**Comment by hverr** [comment]
I'd be happy to accept a PR!

**Comment by hverr** [comment]
When you prepare the PR could you add the following line to the docs:

```
Note that the member check and conditional execution of the action is not one atomic action.
```

or something similar, thanks.

**Comment by cdupont** [comment]
I did the pull request!
