### ISSUE TITLE
newCache should avoid STM

### ISSUE THREAD

**Issue by tebello-thejane** [hverr/haskell-cache#3]
In particular, if you use `unsafePerformIO` to create a top-level `Cache`, you run the risk of triggering a runtime `Control.Concurrent.STM.atomically was nested` exception.

I believe this can be mitigated by using `newTVarIO` instead of `newTVar` to create the cache.

I'll give it a whirl and submit a pull request.

**Comment by hverr** [comment]
Awesome thanks!

**Comment by hverr** [comment]
Fixed in [cache-0.1.0.1](https://hackage.haskell.org/package/cache-0.1.0.1)
